Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.Neos.Form.FormHandlerFinisher: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Neos.Form.FormHandlerFinisher:
            - Modules

  Form:
    presets:
      default:
        finisherPresets:
          'NeosRulez.Neos.Form.FormHandlerFinisher:FormHandlerFinisher':
            implementationClassName: NeosRulez\Neos\Form\FormHandlerFinisher\Finishers\FormHandlerFinisher
            options: { }
      bootstrap:
        finisherPresets:
          'NeosRulez.Neos.Form.FormHandlerFinisher:FormHandlerFinisher':
            implementationClassName: NeosRulez\Neos\Form\FormHandlerFinisher\Finishers\FormHandlerFinisher
            options: {  }
